### ISSUE TITLE
Explicit/Implicit TrainingData read access to data

### ISSUE THREAD

**Issue by tylertownsend** [nasa/bingo#27]
In implicit and explicit training data, the parameters of x and y (or dx_dt for implicit) are passed to the constructor to create a new instance. However, the constructor verifies that the data is shaped correctly. Because the member variables are exposed for both read and write access, this reshaping can be skipped and the data structure can be broken. Add read only properties to the values.

**Comment by gbomarito** [comment]
finally got around to implementing this, thanks
