### ISSUE TITLE
Feature request: add a comparison of BINGO with other genetic algorithm + symbolic regression packages in the README

### ISSUE THREAD

**Issue by sgbaird** [nasa/bingo#49]
The main one that comes to mind is [gplearn](https://github.com/trevorstephens/gplearn), which I came across in the following article:

> Weng, B.; Song, Z.; Zhu, R.; Yan, Q.; Sun, Q.; Grice, C. G.; Yan, Y.; Yin, W. J. Simple Descriptor Derived from Symbolic Regression Accelerating the Discovery of New Perovskite Catalysts. Nature Communications 2020, 11 (1), 1–8. https://doi.org/10.1038/s41467-020-17263-9.

And of course [some others are out there](https://github.com/search?l=Python&o=desc&q=symbolic+regression&s=stars&type=Repositories).

**Comment by sgbaird** [comment]
@jhochhal

**Comment by sgbaird** [comment]
Another that I came across maybe worth mentioning https://github.com/brendenpetersen/deep-symbolic-optimization

**Comment by gbomarito** [comment]
bingo will be part of the next SRBENCH benchmarking analysis: github.com/cavalab/srbench
