### ISSUE TITLE
How to implement seeding with Bingo

### ISSUE THREAD

**Issue by sgbaird** [nasa/bingo#51]
How/where in the codebase does this get implemented? I assume that this takes the form of artificially imposing certain equations in the initial population gene pool

**Comment by gbomarito** [comment]
At the moment there is no automated scheme for doing this. We may choose to incorporate an automated method in the future but right now it is out of scope.

One method for performing population seeding might look like this:
1) generate a/some AGraphs based on string form (or sympy equations) of the equations you want to use for seeding
2) optionally, use mutation and crossover operations to vary the group of AGraphs
3) replace the population of an EvolutionaryOptimizer (e.g. Island) to your set of equations
